projectcalico/calico-kubernetes

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
move PR from old repo (https://github.com/Metaswitch/calico-docker/pull/401)
> Calico Policy in Kubernetes Annotations

- calico_kubernetes/calico_kubernetes.py
> Diagnostics when auth with API server fails

- calico_kubernetes/calico_kubernetes.py
> Search for calicoctl in user's PATH by default.

- calico_kubernetes/calico_kubernetes.py
* Remove an unused import
* Tidy up string expansion in logging statements
> Minor fixes

- .gitignore
- calico_kubernetes/calico_kubernetes.py
> Log out exceptions thrown in the plugin

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/logutils.py
Also includes a refactor to keep line lengths less than 79 characters.
> Log INFO and above to stdout

- calico_kubernetes/calico_kubernetes.py
* Tidy up a logging statement
* Remove some unnecessary whitespace
> Minor fixes to calico_kubernetes.py

- calico_kubernetes/logutils.py
#66
Change the FileHandler to rotate when the file gets sufficiently large.
> Use Rotating File Handler for logs

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
> Improve Code Coverage

- README.md
consistent with that of calico-docker
> Update Calico Badges in README

- config/master/calico-etcd.manifest
- config/master/calico-node.service
- config/master/kubelet.service
- config/master/kubernetes-master.manifest
- config/node/calico-node.service
- config/node/kube-proxy.service
- config/node/kubelet.service
- config/node/network-environment-template
Adds the config required for https://github.com/kubernetes/kubernetes/pull/16204#issuecomment-150708029
> Add deployment config

- build_calico_kubernetes/Dockerfile
- build_calico_kubernetes/requirements.txt
- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/logutils.py
- calico_kubernetes/tests/kube_plugin_test.py
+ Fix #72
+ Use custom LoggerAdapter class to update the logger object with processed message after docker_id has been found.
> Append Docker ID to logging messages

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
> Catch exceptions when logging interfaces

- calico_kubernetes/calico_kubernetes.py
> Change CALICO_IPAM default to "true"

- config/cloud-config/master-config-template.yaml
- config/cloud-config/node-config-template.yaml
Depends on Kubernetes v1.1 release - don't merge until released.
Config used by: https://github.com/kubernetes/kubernetes/pull/16380
> [WIP] Add cloud-config files for CoreOS demo

- build_calico_kubernetes/requirements.txt
Fixes an etcd consistency issue: https://github.com/projectcalico/libcalico/issues/47
> Bump libcalico to v0.5.0

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/logutils.py
- calico_kubernetes/tests/kube_plugin_test.py
Simplifies logging logic - still need to test this.
> Log to stderr instead of stdout.

- config/cloud-config/master-config-template.yaml
- config/cloud-config/node-config-template.yaml
- config/master/kubernetes-master.manifest
+ Calico-node v0.12.0
+ Calico-kubernetes v0.6.1
> Update config to use Kube v1.1.1

- config/node/calico-node.service
> calico-kubernetes 0.6.1

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
Adds the ability to specify `DEFAULT_POLICY=none`, thus disabling all policy in the plugin.
Annotations will not be used to generate policy, and no namespace isolation will be enforced.
This mode does not require the `apiserver` to be running, and does not query the API at all.
> Option to disable all policy

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
> Validate container state at beginning of create() hook

- Makefile
- Add coverage
- deal with user not be UID 1000
- Use the fact that the calico/test container now has the requried modules
> Fix previous build fixes

- calico_kubernetes/policy.py
- calico_kubernetes/tests/policy_test.py
Wait for https://github.com/projectcalico/libcalico/pull/53 to get it
> Remove validation done in libcalico

- Makefile
Never use a stale build container again!
> Add docker pull command to make target

- calico_kubernetes/calico_kubernetes.py
- calico_kubernetes/tests/kube_plugin_test.py
> Cleanup when we fail to setup neworking
